In [1]:
import retro        # pip install gym-retro
import numpy as np  # pip install numpy
import cv2          # pip install opencv-python
import neat         # pip install neat-python
import pickle       # pip install cloudpickle

In [2]:

class Worker(object):
    def __init__(self, genome, config):
        self.genome = genome
        self.config = config
        
    def work(self):
        
        self.env = retro.make('SuperMarioWorld-Snes')
        
        self.env.reset()
        
        ob, _, _, _ = self.env.step(self.env.action_space.sample())
        
        inx = int(ob.shape[0]/6)
        iny = int(ob.shape[1]/6)
        done = False
        
        net = neat.nn.FeedForwardNetwork.create(self.genome, self.config)
        
        fitness = 0
        xpos_max = 0
        counter = 0
        
        while not done:
            self.env.render()
            ob = cv2.resize(ob, (inx, iny))
            #ob = cv2.cvtColor(ob, cv2.COLOR_BGR2GRAY)
            #ob = np.reshape(ob, (inx, iny))
            imgarray = np.ndarray.flatten(ob)
            imgarray = np.interp(imgarray, (0, 254), (-1, +1))

            actions = net.activate(imgarray)
            ob, rew, done, info = self.env.step(actions)
            
            xpos = info['score']
            print(xpos)
            if xpos > xpos_max:
                xpos_max = xpos
                counter = 0
                print(xpos)
                fitness += xpos + 1
            else:
                counter += 1
                fitness += 1
                
            if counter > 250:
                done = True

        return fitness


def eval_genomes(genome, config):
    
    worky = Worker(genome, config)
    return worky.work()



In [4]:
config = neat.Config(neat.DefaultGenome, neat.DefaultReproduction,
                     neat.DefaultSpeciesSet, neat.DefaultStagnation,
                     'config-feedforward')

p = neat.Population(config)

p.add_reporter(neat.StdOutReporter(True))
stats = neat.StatisticsReporter()
p.add_reporter(stats)
#p.add_reporter(neat.Checkpointer(10))
#p = neat.Checkpointer.restore_checkpoint('./neat-checkpoint-603')
#p.run(eval_genomes, 1)
pe = neat.ParallelEvaluator(10, eval_genomes)

Se prendio


In [ ]:
winner = p.run(pe.evaluate, 100)


 ****** Running generation 0 ****** 



In [ ]:
with open('winner.pkl', 'wb') as output:
    pickle.dump(winner, output, 1)

In [1]:
import retro

def main():
    env = retro.make(game='Airstriker-Genesis')
    obs = env.reset()
    i = 0
    done = False
    while not done:
        print(env.action_space.sample())
        obs, rew, done, info = env.step([0,1,0,0,0,0,0,0,0,0,0,0])
        env.render()
        if done:
            obs = env.reset()
        i+=1
    env.close()


if __name__ == "__main__":
    main()

[0 1 1 0 0 0 0 1 1 0 1 1]
[0 1 0 0 1 1 0 1 1 0 0 1]
[0 0 0 1 0 1 0 1 1 0 1 0]
[1 1 1 0 1 1 0 1 1 0 1 1]
[1 1 1 0 0 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 0 1 0 1 0]
[0 1 0 0 0 1 0 1 0 0 0 0]
[1 1 0 0 1 0 1 1 0 0 1 1]
[0 1 1 1 0 0 0 1 0 1 0 1]
[0 0 0 1 1 0 0 0 1 1 0 1]
[1 0 0 1 0 1 0 0 0 1 0 1]
[1 1 1 0 1 0 0 1 1 1 0 0]
[0 0 1 0 0 1 0 0 0 1 0 0]
[0 1 0 0 1 0 0 1 1 0 1 1]
[0 0 0 1 1 1 0 1 0 1 1 0]
[1 0 0 0 1 1 1 1 0 1 0 0]
[1 1 1 0 0 0 0 1 0 1 1 0]
[1 0 1 1 1 0 0 1 1 0 1 1]
[1 0 0 0 0 1 0 1 1 0 0 1]
[1 1 1 0 0 0 0 1 1 0 1 1]
[0 0 1 0 0 1 0 0 0 1 1 0]
[1 1 1 1 1 1 1 0 0 0 0 1]
[1 0 0 0 0 1 0 0 0 0 1 0]
[0 0 0 1 1 0 1 0 1 1 0 1]
[0 1 1 0 1 0 0 1 0 0 1 1]
[1 1 1 0 0 1 0 1 0 0 0 0]
[0 0 1 0 1 0 0 1 0 1 0 0]
[1 1 0 1 0 1 0 0 1 0 1 0]
[1 0 0 1 0 1 0 1 1 1 1 1]
[1 0 0 1 1 1 0 1 0 1 1 1]
[0 1 0 0 1 1 0 0 1 0 1 0]
[0 0 0 0 1 1 1 0 0 0 0 1]
[1 1 1 0 0 0 1 1 0 1 0 0]
[0 1 1 0 1 1 1 1 0 0 1 1]
[1 0 0 0 1 1 0 0 0 1 0 1]
[0 1 0 1 1 1 0 1 1 1 0 1]
[0 0 1 1 0 0 1 1 0 1 1 1]
[1 1 0 1 0 1 0 0 1 0 1 1]
[1 1 1 1 0 1

[0 1 0 0 0 0 0 0 1 0 0 1]
[0 0 1 1 0 0 1 1 1 1 0 1]
[0 0 0 1 1 1 0 0 0 1 1 0]
[0 1 0 0 1 1 0 0 0 0 0 0]
[0 1 1 0 0 1 1 0 1 0 1 1]
[0 1 1 0 0 0 1 0 0 1 1 0]
[0 1 0 1 1 1 1 0 0 0 1 1]
[1 1 1 0 0 1 1 0 0 0 0 0]
[0 1 0 0 1 0 0 0 1 1 0 0]
[0 0 0 1 1 1 1 1 1 1 1 0]
[1 0 0 1 0 1 1 1 0 0 1 1]
[0 0 0 1 1 1 0 0 1 1 0 1]
[0 0 0 1 1 1 1 1 1 0 0 1]
[0 1 1 0 0 0 0 1 1 1 0 0]
[1 0 0 1 0 0 0 0 1 0 1 0]
[0 1 0 0 0 0 1 0 1 0 1 0]
[1 1 1 0 1 0 0 0 1 0 0 0]
[0 0 1 0 1 0 0 0 1 1 1 0]
[1 0 0 0 1 0 0 0 1 0 1 1]
[1 1 0 0 0 0 0 1 0 0 1 1]
[0 1 0 0 0 1 0 1 1 1 0 0]
[1 0 1 1 0 1 1 1 1 0 0 0]
[0 0 1 1 1 1 0 0 1 0 0 0]
[0 1 1 1 1 1 1 1 0 1 0 0]
[0 0 1 1 1 1 0 1 0 0 1 0]
[0 0 0 0 0 0 1 0 1 1 1 1]
[0 1 1 0 1 0 0 0 0 0 1 0]
[0 1 0 0 0 0 0 0 0 0 0 1]
[0 0 1 0 1 0 0 0 1 0 0 1]
[1 1 0 1 1 1 1 1 0 0 0 0]
[0 0 1 0 1 1 1 1 0 1 0 0]
[1 0 0 1 0 1 0 0 0 1 0 0]
[1 0 1 1 0 0 1 1 1 1 0 1]
[0 0 1 0 1 0 1 1 1 1 1 0]
[0 1 1 0 0 1 0 1 0 1 0 0]
[0 1 1 0 0 0 1 1 1 1 1 1]
[1 1 0 0 0 0 1 0 1 1 1 1]
[0 1 0 0 0 0 0 1 1 0 0 0]
[0 1 1 0 0 1

[1 1 0 0 0 1 1 0 0 0 0 0]
[0 0 0 0 0 1 0 0 1 1 0 1]
[0 1 1 0 0 1 1 0 0 0 1 0]
[0 1 0 1 1 0 1 0 0 1 0 0]
[1 1 0 0 0 1 1 1 0 0 0 1]
[0 1 1 1 0 1 0 0 1 1 1 1]
[1 0 1 0 0 1 1 1 0 0 0 1]
[0 1 0 0 0 1 1 1 1 1 1 0]
[1 1 0 0 0 1 0 1 1 1 0 1]
[0 0 0 1 1 1 1 1 0 1 1 1]
[1 1 0 0 1 0 0 0 0 0 0 0]
[0 1 1 1 0 0 1 0 1 0 0 1]
[1 1 1 0 0 0 0 0 0 0 0 0]
[0 0 1 1 1 1 0 1 0 0 0 0]
[0 1 1 0 1 0 1 0 0 1 0 0]
[0 1 1 0 0 1 0 1 0 1 0 1]
[0 0 0 0 1 0 1 1 0 0 1 1]
[0 1 0 0 0 1 0 1 1 1 1 1]
[1 1 0 1 1 1 0 1 0 1 1 1]
[0 0 1 1 1 0 1 1 1 0 0 1]
[0 0 0 0 1 1 1 0 0 1 1 0]
[0 1 0 1 1 1 1 1 1 0 1 0]
[0 1 1 0 0 0 1 0 0 1 1 0]
[0 0 0 0 0 1 1 0 1 0 0 1]
[0 1 0 1 0 0 1 1 0 1 1 0]
[0 0 1 0 1 1 0 0 1 1 0 1]
[0 0 1 0 0 1 0 0 0 0 0 1]
[1 1 1 0 0 1 0 1 1 1 1 0]
[0 1 1 1 0 0 0 1 0 1 0 1]
[0 1 1 1 0 1 1 1 1 1 1 0]
[1 0 1 1 1 0 0 1 1 0 1 1]
[1 0 1 0 1 1 1 0 1 1 1 0]
[1 0 0 1 1 0 1 0 0 1 1 1]
[0 1 1 0 0 0 1 1 0 1 0 0]
[1 0 0 0 1 1 0 0 1 1 0 1]
[1 0 1 0 0 1 1 1 0 1 1 1]
[1 0 1 1 1 1 1 1 1 0 0 1]
[1 1 0 0 1 1 1 1 0 0 0 0]
[0 0 1 1 0 0

[1 1 0 0 1 1 0 1 1 1 0 1]
[0 1 1 0 0 0 0 1 1 1 1 1]
[1 1 0 1 0 0 1 1 0 1 1 0]
[0 1 0 1 0 0 0 0 0 0 0 1]
[0 1 0 1 0 1 0 0 0 0 1 1]
[1 1 0 1 0 1 0 1 1 0 0 0]
[1 0 1 1 0 0 0 1 0 0 1 1]
[1 1 0 0 1 1 0 0 0 0 1 1]
[0 1 0 0 0 1 0 1 0 0 1 1]
[0 1 0 0 1 0 1 1 0 0 1 1]
[0 0 1 1 0 1 0 0 1 1 1 0]
[1 1 0 1 0 0 0 0 0 1 1 1]
[1 1 1 1 1 0 0 0 1 1 1 0]
[0 0 1 0 0 1 1 1 0 0 1 0]
[0 0 1 1 0 1 0 0 0 1 1 0]
[0 1 0 1 0 1 0 1 1 1 0 1]
[1 1 0 1 1 1 1 1 0 1 1 1]
[0 0 0 1 1 0 0 0 0 1 0 0]
[1 1 0 1 0 1 1 0 0 0 1 0]
[1 0 1 0 1 0 1 1 0 0 0 0]
[0 0 1 1 1 0 0 1 1 0 1 0]
[1 0 0 0 1 1 0 0 1 1 0 0]
[1 0 1 1 0 0 1 1 0 0 1 1]
[0 0 1 1 0 0 0 1 1 0 1 1]
[0 1 0 1 1 1 1 0 0 1 0 0]
[0 1 1 1 0 1 1 1 1 1 0 0]
[0 1 1 0 0 1 1 1 0 0 0 1]
[1 0 0 1 0 0 1 1 0 1 1 1]
[1 1 1 1 0 0 1 1 0 0 0 1]
[1 0 1 0 1 1 1 1 1 1 0 1]
[1 1 1 1 0 0 1 1 1 0 0 0]
[0 0 0 0 1 1 1 1 0 1 0 0]
[1 1 1 0 0 1 0 1 0 1 1 0]
[1 1 1 1 0 1 1 1 0 1 1 0]
[1 1 0 1 1 1 0 0 1 1 1 1]
[0 1 1 0 1 0 0 0 0 1 1 1]
[0 0 0 1 1 1 1 0 0 1 1 0]
[0 1 1 0 0 1 0 0 0 0 0 1]
[1 0 0 1 1 0